modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com/Talia-12/Spellcore/issues"

[[mods]]
modId = "spellcore"
version = "${file.jarVersion}"
displayName = "Spellcore"
displayURL = "https://github.com/Talia-12/Spellcore"
logoFile = "logo.png"
credits = ""
authors = "Talia"
description = "This is my own shot at a magic mod in Minecraft with a more atomic feel. This one is going to be based around cellular automota, Game of Life esque, though more complicated."

[[dependencies.spellcore]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spellcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spellcore]]
modId = "patchouli"
mandatory = true
versionRange = "[1.19.2-77,)"
ordering = "NONE"
side = "BOTH"